### ISSUE TITLE
Find minimum and maximum element in an array

### ISSUE THREAD

**Issue by samarth2727** [samarth2727/DataStructure#1]
-> Find the minimum and maximum elements in an array.
-> code should be with proper comments.
-> Language: C++

**Comment by PuneetDabral** [comment]
sir can i

**Comment by PuneetDabral** [comment]
sir assign it to me ??!!

**Comment by samarth2727** [comment]
assigned to you.

**Comment by PuneetDabral** [comment]
sir now tell me what i can do!!

**Comment by PuneetDabral** [comment]
can i made a program to Find minimum and maximum element in an array in c++

**Comment by samarth2727** [comment]
yes. read the first comment.

**Comment by PuneetDabral** [comment]
ok sir i will send a pull request after some time
